create table client
(
    id        int8 generated by default as identity,
    end_ban   timestamp,
    is_active boolean default true  not null,
    is_block  boolean default false not null,
    login     varchar(255)          not null,
    password  varchar(255)          not null,
    role      varchar(32),
    start_ban timestamp,
    primary key (id)
);

create table client_rooms
(
    client_id int8 not null,
    room_id   int8 not null,
    primary key (client_id, room_id)
);

create table message
(
    id            int8 generated by default as identity,
    content       varchar(1024) not null,
    creation_time timestamp,
    client_id     int8        not null,
    room_id       int8,
    primary key (id)
);

create table room
(
    id         int8 generated by default as identity,
    is_private boolean      not null,
    room_name  varchar(255) not null,
    client_id  int8       not null,
    primary key (id)
);

alter table client
    add constraint client_login_unique
    unique (login);

alter table room
    add constraint room_name_unique
    unique (room_name);

alter table client_rooms
    add constraint client_rooms_room_fk
    foreign key (room_id) references room;

alter table client_rooms
    add constraint client_rooms_client_fk
    foreign key (client_id) references client;

alter table message
    add constraint message_client_fk
    foreign key (client_id) references client;

alter table message
    add constraint message_room_fk
    foreign key (room_id) references room;

alter table room
    add constraint room_client_fk
    foreign key (client_id) references client;
